// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNPMTAbLwJZe7-N63jKP9qizL4L-DhOow',
    appId: '1:1001995963457:web:5b6b15649e80be670e0ac0',
    messagingSenderId: '1001995963457',
    projectId: 'fluidity-f9e2f',
    authDomain: 'fluidity-f9e2f.firebaseapp.com',
    storageBucket: 'fluidity-f9e2f.firebasestorage.app',
    measurementId: 'G-8XVFHL7YET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjpxzuQ-A-rYczF15RyEkfcpGSvo0jPN4',
    appId: '1:1001995963457:android:c2cd408160cb72c10e0ac0',
    messagingSenderId: '1001995963457',
    projectId: 'fluidity-f9e2f',
    storageBucket: 'fluidity-f9e2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf66uAT5mq3iaR67lInRRNVJbQ46cry_I',
    appId: '1:1001995963457:ios:7a8ae44697292c590e0ac0',
    messagingSenderId: '1001995963457',
    projectId: 'fluidity-f9e2f',
    storageBucket: 'fluidity-f9e2f.firebasestorage.app',
    iosBundleId: 'com.example.fluidity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf66uAT5mq3iaR67lInRRNVJbQ46cry_I',
    appId: '1:1001995963457:ios:7a8ae44697292c590e0ac0',
    messagingSenderId: '1001995963457',
    projectId: 'fluidity-f9e2f',
    storageBucket: 'fluidity-f9e2f.firebasestorage.app',
    iosBundleId: 'com.example.fluidity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNPMTAbLwJZe7-N63jKP9qizL4L-DhOow',
    appId: '1:1001995963457:web:bfe29f608983f0060e0ac0',
    messagingSenderId: '1001995963457',
    projectId: 'fluidity-f9e2f',
    authDomain: 'fluidity-f9e2f.firebaseapp.com',
    storageBucket: 'fluidity-f9e2f.firebasestorage.app',
    measurementId: 'G-7X8R4HD2XK',
  );
}
